# Generated by Django 4.0.6 on 2022-08-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('horas', models.TextField()),
                ('creditos', models.TextField()),
                ('Fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
